### ISSUE TITLE
Snapshot feat. fails to work if user has an old IndexDB that lacks the `snapshots` table

### ISSUE THREAD

**Issue by EvitanRelta** [EvitanRelta/markgh#105]
If the user has tested an older version of the webapp before the snapshot feature was introduced,
their save IndexDB will lack the `snapshot` table,
which stops the snapshot feature from working and gives the following console error when loading the page:
![image](https://user-images.githubusercontent.com/35413456/176890503-31440184-3658-414b-8b0c-7eb64ab4035c.png)

A temp solution has been implemented for Milestone 2's demo at 13f4d7707c5bbf4a39257f1f7caea12d14bc3284

**Comment by swxk19** [comment]
Temp solution is sufficient, just needs to have more specific error handling

**Comment by EvitanRelta** [comment]
The temp fix only works if the `snapshot` table is missing. 
We probably should have [incremented the database version](https://dexie.org/docs/Tutorial/Design#database-versioning) when modifying the structure of the database.

Without that database-versioning, more bugs have been popping up like: #130
