### ISSUE TITLE
Option to merge and delete branch 

### ISSUE THREAD

**Issue by swxk19** [EvitanRelta/markgh#170]
After user has pushed via our site, currently they are given a redirect link to the PR.
An option can be added to merge and delete the branch directly from our site, for convenience (deleting branches through GitHub takes a few steps)

**Comment by swxk19** [comment]
Is this too invasive? it's the user's choice

**Comment by EvitanRelta** [comment]
> Is this too invasive? it's the user's choice

kinda
I ain't gonna let some bot or script auto-sell my anime NFTs lmao

**Comment by swxk19** [comment]
gg
