### ISSUE TITLE
UI Tweaks

### ISSUE THREAD

**Issue by swxk19** [EvitanRelta/markgh#183]
- Refine 'PushGHDialog'
- Refine toolbar
- Hotkey in tooltip for format options
- Freeze header
- Format option color changes if toggled active
- Hide 'ImageContainer'
- Other minor repositions

**Comment by EvitanRelta** [comment]
The `feature`, `bug`, `refactor`, `improvement` Issue labels should be mutually exclusive (ie. if u have 1 of them, u can't have the others).
