### ISSUE TITLE
Replace all (or as many as possible) JSX elements with MUI counterparts

### ISSUE THREAD

**Issue by EvitanRelta** [EvitanRelta/markgh#29]
Currently, a mix of regular JSX elements and MUI components are being used.
Which can cause problems when changing colorschemes/MUI-themes later on, as the JSX elements might not inherit the color changes.

_**For example:** `div` can be swapped out with MUI's `Box` or `Container`_

![image](https://user-images.githubusercontent.com/35413456/173571285-0b7d4a37-89a1-4ef4-b56a-65d72ec6c0f9.png)

**Comment by swxk19** [comment]
Completed this on my `refactor-elements-to-mui` branch on my fork. Awaiting PR for `feat-git-clone` branch to merge before rebasing this and submitting PR
