### ISSUE TITLE
Switching editor lib as QuillJS is dead

### ISSUE THREAD

**Issue by EvitanRelta** [EvitanRelta/markgh#3]
QuillJS hasn't had any release since 2019. A few of their recent pull-request have been approved _(indicating some activity)_, but there's currently 1.1k open issues _(indicating the repo isn't well-maintained)_ and there's no release date for the next version _(v2.0.0)_. There's also many Issues on their Github asking if QuillJS is dead (eg. [1](https://github.com/quilljs/quill/issues/3521), [2](https://github.com/quilljs/quill/issues/2475), [3](https://github.com/quilljs/quill/issues/3359), [4](https://github.com/quilljs/quill/issues/3112))

The documentation for customisation is also IMO lacking.

There's also features that we need _(eg. image resizing, insert image via URL, nested codeblocks/quotes, set language for syntax highlighting etc.)_ that QuillJS doesn't support; and many 3rd-party QuillJS modules that implements those feats. _(eg. [quill-image-resize-module](https://github.com/kensnyder/quill-image-resize-module))_ are outdated and don't work anymore.

Thus, we should switch our rich-text editor library. Some libraries were suggested on a [QuillJS's issue](https://github.com/quilljs/quill/issues/3359), including:

- [TipTap](https://github.com/ueberdosis/tiptap)
- [Editor.js](https://github.com/codex-team/editor.js)
- [Jodit](https://github.com/xdan/jodit) _(or its [React Wrapper ver.](https://github.com/jodit/jodit-react))_

**Comment by EvitanRelta** [comment]
Successfully migrated to [TipTap](https://github.com/ueberdosis/tiptap) editor.

**Comment by GaelPaquet** [comment]
TipTap seems dying too...

**Comment by EvitanRelta** [comment]
> TipTap seems dying too...

oh shit its our first non-collaborator comment :O
and ohshit TipTap's dying too?
